# Generated by Django 3.2.5 on 2022-02-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appointment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('IP', 'In Progress'), ('AC', 'Accepted'), ('RE', 'Rejected'), ('CD', 'Canceled'), ('GR', 'Graduate')], default='IP', max_length=2),
        ),
    ]
